AWSTemplateFormatVersion: 2010-09-09
#Create EC2 Instances in Public and Private Subnets

Parameters:
  MyKeyPair:
    Description: Chon Key Pair de SSH vao EC2
    Type: AWS::EC2::KeyPair::KeyName
    # Default: 2352xxxx

  AmiId:
    Description: AMI ID for EC2 Instances
    Type: AWS::EC2::Image::Id
    # Default: ami-0c398cb65a93047f2  # Amazon Linux 2 in us-east-1

  PublicSubnetId:
    Description: Subnet ID for Public EC2
    Type: AWS::EC2::Subnet::Id
    # Default: !ImportValue Group09PublicSubnetId
  
  PrivateSubnetId:
    Description: Subnet ID for Private EC2
    Type: AWS::EC2::Subnet::Id
    # Default: !ImportValue Group09PrivateSubnetId

  PublicSGID:
    Description: Security Group ID for Public EC2
    Type: AWS::EC2::SecurityGroup::Id
    # Default: !ImportValue Group09PublicSGID

  PrivateSGID:
    Description: Security Group ID for Private EC2
    Type: AWS::EC2::SecurityGroup::Id
    # Default: !ImportValue Group09PrivateSGID

  InstanceType:
    Description: EC2 Instance Type
    Type: String
    # Default: t2.micro
    # AllowedValues:
    #   - t2.micro
    #   - t2.small
    #   - t2.medium
    # ConstraintDescription: must be a valid EC2 instance type.

Resources:
  Ec2Public:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AmiId
      InstanceType: !Ref InstanceType
      KeyName: !Ref MyKeyPair
      NetworkInterfaces: 
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          SubnetId: !Ref PublicSubnetId
          GroupSet: 
            - !Ref PublicSGID
      Tags:
        - Key: Name
          Value: ec2-public-group09

  Ec2Private:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0c398cb65a93047f2
      InstanceType: !Ref InstanceType
      KeyName: !Ref MyKeyPair
      NetworkInterfaces: 
        - AssociatePublicIpAddress: "false"  
          DeviceIndex: "0"
          DeleteOnTermination: "true"
          SubnetId: !Ref PrivateSubnetId
          GroupSet: 
            - !Ref PrivateSGID
      Tags:
        - Key: Name
          Value: ec2-private-group09
  